apiVersion: v1
kind: Service
metadata:
  name: nollea-fe
  namespace: nollea
  labels:
    app: nollea-fe
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: nollea-fe