apiVersion: apps/v1
kind: Deployment
metadata:
  name: nollea-be
  namespace: nollea
  labels:
    app: nollea-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nollea-be
  template:
    metadata:
      labels:
        app: nollea-be
    spec:
      imagePullSecrets:
      - name: ghcr-secret 
      containers:
      - name: nollea-be
        image: ghcr.io/go-meong/nollea-be:v0.0.3
        envFrom:
        - configMapRef:
            name: nollea-config
        - secretRef:
            name: nollea-secrets
        ports:
        - containerPort: 8080