apiVersion: v1
kind: Service
metadata:
  name: nollea-be
  namespace: nollea
  labels:
    app: nollea-be
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: nollea-be